packages:
  - packages/*

catalog:
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/adapter-static': ^3.0.8
  '@sveltejs/kit': ^2.50.1
  '@sveltejs/package': ^2.5.7
  '@sveltejs/vite-plugin-svelte': 6.2.4
  '@types/node-emoji': ^1.8.2
  publint: ^0.3.6
  svelte: ^5.49.0
  svelte-check: ^4.3.5
  tslib: ^2.8.1
  typescript: ^5.9.3
  vite: ^7.3.1
